[package]
name = "rustc_feature"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
either = "1.5.0"
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_span = { path = "../rustc_span" }
# tidy-alphabetical-end
